import { state, $, pad, selectedPad, padKey, debounce, toast, activePresetName } from './state.js';
import { refreshBoard, refreshDsp, refreshPresets, refreshSettings, dspSet, presetLoad, presetSave, presetDelete, padPlay, padStop, padImport, padAdd, padUpdate, padsStopAll, settingsSet } from './ipc.js';
import { updatePads } from './ui/board.js';
import { updateRightPanels, renderShell } from './main.js';

export const pushDsp = debounce(async () => { if (state.dsp) await dspSet(state.dsp).catch(() => {}); }, 60);
export const pushPad = debounce(async () => { const p = selectedPad(); if (p) await padUpdate(state.selected.bank, p).catch(() => {}); }, 150);
export async function playPadAction(bank, slot) { const p=pad(bank,slot); if(!p)return; if(!p.path&&!p.duration_ms){state.selected={bank,slot};return importSound(bank,slot);} const key=padKey(bank,slot); state.selected={bank,slot}; if(state.latched.has(key)){await padStop(bank,slot).catch(()=>{});state.latched.delete(key);updatePads();updateRightPanels();return;} try{await padPlay(bank,slot);}catch(err){toast(`Не удалось воспроизвести: ${err}`,true);return;} if(p.play_mode==='loop'||p.play_mode==='toggle')state.latched.add(key);else{state.playing.set(key,true);setTimeout(()=>{if(state.playing.delete(key)&&state.view==='board')updatePads();},Math.max(120,(p.duration_ms||1500)-(p.trim_start_ms||0)));}updatePads();updateRightPanels(); }
export async function importSound(bank,slot) { const b=bank??state.bank,s=slot??state.selected.slot; let path=null; try { path=window.__TAURI__?.dialog?.open?await window.__TAURI__.dialog.open({multiple:false,directory:false,title:'Импорт звука на пад',filters:[{name:'Audio',extensions:['mp3','wav','flac','ogg','aac','m4a']}] }):prompt('Путь к аудиофайлу:'); } catch(_){} if(!path)return; try{const np=await padImport(b,s,path);state.selected={bank:b,slot:np.id};await refreshBoard();updatePads();updateRightPanels();}catch(err){toast(`Не удалось импортировать: ${err}`,true);} }
export async function addPad() { try { const p = await padAdd(state.bank); state.selected = { bank: state.bank, slot: p.id }; await refreshBoard(); updatePads(); updateRightPanels(); } catch (err) { toast(`Не удалось добавить пад: ${err}`, true); } }
export async function applyPreset(name) { try{state.dsp=await presetLoad(name);state.telemetry.active_preset=name;renderShell();toast(`Пресет применён: ${name}.toml`);}catch(err){toast(`Не удалось загрузить пресет: ${err}`,true);} }
export async function deletePreset(name) { if(!confirm(`Удалить ${name}.toml?`))return; try{await presetDelete(name);await refreshPresets();renderShell();}catch(err){toast(`Не удалось удалить: ${err}`,true);} }
export async function saveCurrentAsPreset() { const name=prompt('Имя нового пресета (без .toml):','my_voice');if(!name||!state.dsp)return;const d=state.dsp;const toml=`[meta]\nname = ${JSON.stringify(name)}\ndescription = "Сохранено из DSP панели"\nauthor = "OpenWire"\nversion = 1\n\n[dsp.pitch]\nenabled = ${d.pitch_enabled}\nsemitones = ${d.pitch_semitones}\nformant_shift = ${d.formant_shift}\n\n[dsp.equalizer]\nlow_shelf_gain_db = ${d.eq_low_db}\nmid_freq_hz = ${d.eq_mid_freq}\nmid_gain_db = ${d.eq_mid_gain_db}\nmid_q = ${d.eq_mid_q}\nhigh_shelf_gain_db = ${d.eq_high_db}\n\n[dsp.radio_fx]\nenabled = ${d.radio_enabled}\nbandpass_low_hz = ${d.radio_bp_low_hz}\nbandpass_high_hz = ${d.radio_bp_high_hz}\ndrive_saturation = ${d.radio_drive}\nnoise_floor_db = ${d.radio_noise_db}\n\n[routing]\nducking_attenuation_db = ${d.duck_atten_db}\nsidechain_release_ms = ${d.duck_release_ms}\n`;try{await presetSave(name,toml);await refreshPresets();state.telemetry.active_preset=name;renderShell();toast(`Сохранено: ${name}.toml`);}catch(err){toast(`Не удалось сохранить: ${err}`,true);} }
export function openSettings(){const modal=$('#settingsModal');const s=state.settings??{ducking_enabled:true,monitor_enabled:true};$('#setDucking').checked=s.ducking_enabled!==false;$('#setMonitor').checked=s.monitor_enabled!==false;$('#settingsStatus').classList.add('hidden');modal.classList.remove('hidden');modal.classList.add('flex');}
export function closeSettings(){const modal=$('#settingsModal');if(!modal)return;modal.classList.add('hidden');modal.classList.remove('flex');}
export async function saveSettings(){const payload={ducking_enabled:$('#setDucking').checked,monitor_enabled:$('#setMonitor').checked};try{await settingsSet(payload);await refreshSettings();closeSettings();renderShell();}catch(err){const box=$('#settingsStatus');box.classList.remove('hidden');box.classList.add('text-err');box.textContent=`Не удалось сохранить: ${err}`;}}
export async function stopAll(){await padsStopAll().catch(()=>{});state.playing.clear();state.latched.clear();updatePads();}
export { activePresetName, refreshDsp, refreshPresets };
