import { state, $, selectedPad, debounce, toast as toast_ } from './state.js';
import { dspSet, tauriWin, refreshPresets, refreshBoard, padClear, settingsSet } from './ipc.js';
import { updatePads } from './ui/board.js';
import { updateView, updateRightPanels, renderShell } from './main.js';
import { refreshWaveform } from './ui/props.js';
import { pushDsp, pushPad, playPadAction, importSound, addPad, applyPreset, deletePreset, saveCurrentAsPreset, openSettings, closeSettings, saveSettings, stopAll } from './actions.js';
const DSP_UNITS={pitch_semitones:' st',formant_shift:' ×',eq_low_db:' dB',eq_mid_gain_db:' dB',eq_mid_freq:' Hz',eq_mid_q:'',eq_high_db:' dB',radio_bp_low_hz:' Hz',radio_bp_high_hz:' Hz',radio_drive:'',radio_noise_db:' dB',duck_atten_db:' dB',duck_release_ms:' ms',monitor_volume:' ×',stream_volume:' ×'};
let captureTarget=null,trimDrag=null;
export function registerEvents(){document.addEventListener('click',onClick);document.addEventListener('input',onInput);document.addEventListener('change',onChange);document.addEventListener('keydown',onKeydown);document.addEventListener('pointerdown',onPointerDown);document.addEventListener('pointermove',onPointerMove);document.addEventListener('pointerup',onPointerUp);}
async function onClick(e){const el=e.target.closest('[data-action],[data-nav],[data-bank],[data-pad],[data-preset],[data-lib-load],[data-lib-del],[data-win]');if(!el){if(!e.target.closest('#presetMenu'))$('#presetMenu')?.classList.add('hidden');return;}if(el.dataset.win){const w=tauriWin();if(el.dataset.win==='minimize')await w.minimize();if(el.dataset.win==='maximize')await w.toggleMaximize();if(el.dataset.win==='close')await w.close();return;}if(el.dataset.nav){state.view=el.dataset.nav;renderShell();if(state.view==='library')refreshPresets().then(renderShell).catch(()=>{});return;}if(el.dataset.bank!==undefined){state.bank=+el.dataset.bank;renderShell();return;}if(el.dataset.pad!==undefined){e.preventDefault();playPadAction(state.bank,+el.dataset.pad);return;}if(el.dataset.preset){$('#presetMenu')?.classList.add('hidden');applyPreset(el.dataset.preset);return;}if(el.dataset.libLoad){applyPreset(el.dataset.libLoad);return;}if(el.dataset.libDel){deletePreset(el.dataset.libDel);return;}switch(el.dataset.action){case'panic':stopAll();break;case'open-settings':openSettings();break;case'close-settings':closeSettings();break;case'save-settings':saveSettings();break;case'toggle-preset-menu':$('#presetMenu')?.classList.toggle('hidden');break;case'import':importSound();break;case'add-pad':addPad();break;case'refresh-presets':refreshPresets().then(renderShell).catch(()=>{});break;case'save-current-preset':saveCurrentAsPreset();break;case'clear-pad':{const p=selectedPad();if(p&&confirm(`Очистить пад «${p.name||p.id+1}»?`)){await padClear(state.selected.bank,p.id);await refreshBoard();updatePads();updateRightPanels();}break;}case'capture-hotkey':captureTarget=el;el.textContent='Нажмите клавишу…';el.classList.add('border-accent');break;case'test-pad':{const p=selectedPad();if(p)playPadAction(state.selected.bank,p.id);break;}}}
function onInput(e){const el=e.target;if(el.dataset.dsp&&state.dsp){const v=+el.value;state.dsp[el.dataset.dsp]=v;const out=document.getElementById(`${el.dataset.dsp}Val`);if(out)out.textContent=`${v.toFixed(el.dataset.dsp==='eq_mid_freq'||el.dataset.dsp==='duck_release_ms'?0:2)}${DSP_UNITS[el.dataset.dsp]??''}`;pushDsp();return;}if(el.dataset.padSlider){const p=selectedPad();if(!p)return;p[el.dataset.padSlider]=+el.value/100;const out=document.getElementById(el.dataset.padSlider==='monitor_volume'?'padMonitorVal':'padStreamVal');if(out)out.textContent=`${Math.round(+el.value)}%`;pushPad();return;}if(el.id==='padSearch'){state.search=el.value;updatePads();}}
async function onChange(e){const el=e.target;if(el.dataset.dspBool&&state.dsp){state.dsp[el.dataset.dspBool]=el.checked;pushDsp();return;}if(el.id==='monitorToggle'){if(state.settings){state.settings.monitor_enabled=el.checked;await settingsSet(state.settings).catch(()=>{});}return;}if(el.id==='duckToggle'){if(state.dsp){state.dsp.ducking_enabled=el.checked;await dspSet(state.dsp).catch(()=>{});}if(state.settings)state.settings.ducking_enabled=el.checked;return;}if(el.dataset.padFlag){const p=selectedPad();if(p){p.bass_boost=el.checked;pushPad();}return;}if(el.dataset.padMode!==undefined){const p=selectedPad();if(p){p.play_mode=el.value;updatePads();pushPad();}}}
function onKeydown(e){if(captureTarget){e.preventDefault();e.stopPropagation();const label=normalizeKeyLabel(e),p=selectedPad();if(label==='ESC'){if(p)p.hotkey=null;}else if(label&&p)p.hotkey=label;captureTarget.textContent=p?.hotkey||'Нажмите клавишу…';captureTarget.classList.remove('border-accent');captureTarget=null;if(p)pushPad();updatePads();return;}const inField=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName);if(inField)return;if(e.key==='Escape'){stopAll();return;}const label=normalizeKeyLabel(e);if(!label||e.repeat)return;for(const bank of state.board?.banks??[]){const found=bank.pads.find(p=>(p.hotkey||'').toUpperCase()===label);if(found){playPadAction(found.bank,found.id);return;}}}
function normalizeKeyLabel(e){const named={Escape:'ESC',' ':'SPACE',Enter:'ENTER',Backspace:'BACKSPACE',Delete:'DELETE',Insert:'INSERT',Home:'HOME',End:'END',PageUp:'PAGEUP',PageDown:'PAGEDOWN',ArrowUp:'UP',ArrowDown:'DOWN',ArrowLeft:'LEFT',ArrowRight:'RIGHT',Tab:'TAB'};if(named[e.key])return named[e.key];if(/^F(?:[1-9]|1[0-2])$/.test(e.key))return e.key;if(e.key.length===1)return e.key.toUpperCase();return null;}
function onPointerDown(e){const handle=e.target.closest('#trimStart,#trimEnd');if(!handle)return;const svg=document.getElementById('waveSvg');if(!svg)return;e.preventDefault();trimDrag={which:handle.id,svg};handle.setPointerCapture?.(e.pointerId);}
function onPointerMove(e){if(!trimDrag)return;const {svg,which}=trimDrag;const r=svg.getBoundingClientRect();const x=Math.max(14,Math.min(246,(e.clientX-r.left)/r.width*260));const other=+(which==='trimStart'?svg.dataset.end:svg.dataset.start);const value=which==='trimStart'?Math.min(x,other-2):Math.max(x,other+2);if(which==='trimStart')svg.dataset.start=value;else svg.dataset.end=value;const line=svg.querySelector(which==='trimStart'?'#trimStart line':'#trimEnd line');const rect=svg.querySelector(which==='trimStart'?'#trimStart rect':'#trimEnd rect');line?.setAttribute('x1',value);line?.setAttribute('x2',value);rect?.setAttribute('x',value-3);const shade=svg.querySelector(which==='trimStart'?'#trimShadeA':'#trimShadeB');if(which==='trimStart'){shade?.setAttribute('width',value);}else{shade?.setAttribute('x',value);shade?.setAttribute('width',260-value);}}
const commitTrim=debounce(()=>{const svg=document.getElementById('waveSvg'),p=selectedPad();if(!svg||!p)return;const duration=+svg.dataset.duration||0;if(!duration)return;p.trim_start_ms=Math.round((+svg.dataset.start-14)/232*duration);p.trim_end_ms=Math.round((+svg.dataset.end-14)/232*duration);const label=document.getElementById('trimLabel');if(label)label.textContent=`${p.trim_start_ms}ms → ${p.trim_end_ms}ms`;pushPad();},50);
function onPointerUp(){if(!trimDrag)return;trimDrag=null;commitTrim();}
