import { state, esc, activePresetName } from '../state.js';

export function titlebar() {
  return `<header data-tauri-drag-region class="h-[44px] shrink-0 bg-bar border-b border-line px-[14px] flex items-center gap-3">
    <div data-tauri-drag-region class="flex items-center gap-2"><img src="app-icon.svg" alt="OpenWire" class="w-[22px] h-[22px]" /><span class="text-hi font-extrabold text-[14px] tracking-tight">OpenWire</span><span class="font-mono text-[9px] text-dim border border-line rounded px-1.5 py-[2px] bg-inset">PIPEWIRE LOW-LATENCY</span></div>
    <div class="flex-1 flex items-center justify-center gap-4">${vuMeter('micVU', 'MIC IN')}${vuMeter('outVU', 'STREAM OUT')}</div>
    <div class="flex items-center gap-2"><button data-action="panic" class="stripes-red border border-err/70 text-err hover:bg-err/10 rounded px-2.5 py-1 font-mono text-[10px] tracking-wider">ESC: СТОП</button><div class="flex items-center gap-1 ml-1"><button data-win="minimize" class="w-6 h-6 rounded hover:bg-surf2 text-mut">–</button><button data-win="maximize" class="w-6 h-6 rounded hover:bg-surf2 text-mut">▢</button><button data-win="close" class="w-6 h-6 rounded hover:bg-err/20 text-mut">✕</button></div></div>
  </header>`;
}
function vuMeter(id, label) { return `<div class="flex items-center gap-2"><span class="font-mono text-[9px] text-dim w-[62px] text-right">${label}</span><div class="w-[168px] h-[7px] bg-inset border border-line rounded-sm overflow-hidden"><div id="${id}" class="h-full w-0 transition-[width] duration-75 bg-accent"></div></div><span id="${id}Clip" class="vu-clip w-2 h-2 rounded-full bg-surf2 border border-line" title="CLIP"></span></div>`; }
const NAV = [{ id:'board', label:'Звуковая доска', icon:'▦' }, { id:'dsp', label:'DSP Голос и эффекты', icon:'≋' }, { id:'library', label:'Библиотека пресетов', icon:'⌸', sub:'~/Документы' }];
export function sidebar() { const d = state.dsp ?? {}; return `<aside class="w-[216px] shrink-0 bg-bar border-r border-line p-[10px] flex flex-col gap-3"><div class="bg-surf border border-line rounded p-2.5 space-y-2"><div class="flex items-center justify-between"><span class="font-mono text-[10px] text-mut">MIC INPUT</span><span id="micLed" class="w-1.5 h-1.5 rounded-full bg-ok"></span></div><div class="font-mono text-[10px] text-dim">OpenWire Virtual Mic · 48kHz f32</div><label class="flex items-center justify-between cursor-pointer"><span class="text-[11px] text-body">Слышать себя</span><input id="monitorToggle" type="checkbox" class="accent-accent" ${state.settings?.monitor_enabled === false ? '' : 'checked'} /></label><label class="flex items-center justify-between cursor-pointer"><span class="text-[11px] text-body">Ducking</span><span class="flex items-center gap-1.5"><span class="font-mono text-[10px] text-accent" id="duckDbLabel">${(d.duck_atten_db ?? -12).toFixed(0)}dB</span><input id="duckToggle" type="checkbox" class="accent-ok" ${d.ducking_enabled === false ? '' : 'checked'} /></span></label></div><nav class="flex flex-col gap-1">${NAV.map(n => { const active=state.view===n.id; return `<button data-nav="${n.id}" class="text-left flex items-center gap-2 px-2.5 py-2 rounded text-[12px] ${active?'bg-surf2 text-hi border border-strong':'text-mut hover:bg-surf border border-transparent'}"><span class="${active?'text-accent':'text-ghost'}">${n.icon}</span><span class="flex-1 truncate">${n.label}</span>${n.sub?`<span class="font-mono text-[8px] text-ghost">${n.sub}</span>`:''}</button>`; }).join('')}</nav><div class="mt-auto"><button data-action="open-settings" class="w-full text-left flex items-center gap-2 px-2.5 py-2 rounded text-[12px] text-mut hover:bg-surf border border-transparent"><span class="text-ghost">⚙</span> Настройки</button></div></aside>`; }
export function toolbar() { return `<div class="h-[48px] shrink-0 border-b border-line px-[14px] flex items-center gap-3"><div class="font-mono text-[10px] text-dim">BANK</div><div class="flex gap-1">${[0,1,2,3].map(i=>`<button data-bank="${i}" class="px-2 py-1 rounded text-[10px] font-mono ${state.bank===i?'bg-accent text-app':'bg-surf2 text-mut hover:bg-hover'}">${i+1}</button>`).join('')}</div><div class="h-4 w-px bg-line"></div><button data-action="toggle-preset-menu" class="px-2.5 py-1 rounded border border-line hover:border-hover text-[10px] text-mut">Пресет ▾</button><div id="presetMenu" class="hidden absolute top-[76px] left-[250px] z-30 w-[230px] bg-bar border border-strong rounded shadow-xl p-1">${state.presets.map(p=>`<button data-preset="${esc(p)}" class="block w-full text-left px-2 py-1.5 rounded text-[11px] text-body hover:bg-surf2">${esc(p)}</button>`).join('')||'<span class="block px-2 py-1.5 text-[10px] text-ghost">Нет пресетов</span>'}</div><span class="font-mono text-[10px] text-accent truncate" id="presetName">${esc(activePresetName())}</span><div class="flex-1"></div><input id="padSearch" placeholder="поиск звука…" class="w-[180px] bg-inset border border-line rounded px-2 py-1 text-[11px] text-body outline-none focus:border-hover" /><button data-action="import" class="px-2.5 py-1 rounded bg-accent hover:bg-accent-hover text-app text-[11px] font-semibold">＋ Импорт</button></div>`; }
export function statusbar() { const t=state.telemetry; return `<div class="h-[34px] shrink-0 bg-bar border-t border-line px-[14px] flex items-center gap-3 font-mono text-[10px] text-dim overflow-hidden whitespace-nowrap"><span id="sbPw">PipeWire ${esc(t.pipewire_version||'…')}</span><span class="text-ghost">|</span><span id="sbQuantum">Quantum: ${t.quantum||'—'}</span><span class="text-ghost">|</span><span id="sbLatency">Latency: ${t.quantum?t.latency_ms.toFixed(1)+'ms':'—'}</span><span class="text-ghost">|</span><span>Voices: <span id="sbVoices" class="text-ok">${t.active_voices??0}</span></span><span class="text-ghost">|</span><span class="truncate">Active Voice: <span id="sbPreset" class="text-accent">${esc(activePresetName())}</span></span><span class="text-ghost">|</span><span id="sbEngine">${t.engine_running===false?'PipeWire offline':'Audio: Ready'}</span></div>`; }
export function settingsModal() { return `<div id="settingsModal" class="hidden fixed inset-0 bg-black/60 backdrop-blur-sm items-center justify-center z-50"><div class="w-[420px] bg-bar border border-strong rounded-lg shadow-2xl overflow-hidden"><div class="h-[44px] px-4 flex items-center border-b border-line"><span class="text-hi text-[12px] font-bold">НАСТРОЙКИ PIPEWIRE</span><div class="flex-1"></div><button data-action="close-settings" class="text-ghost hover:text-hi">✕</button></div><div class="p-4 space-y-3"><label class="flex items-center gap-2 text-[11px] text-mut"><input id="setMonitor" type="checkbox" class="accent-accent" /> Слышать себя в наушниках</label><label class="flex items-center gap-2 text-[11px] text-mut"><input id="setDucking" type="checkbox" class="accent-ok" /> Ducking включён</label><p class="font-mono text-[10px] text-ghost">Низкая задержка: PipeWire quantum 64/48000.</p><div id="settingsStatus" class="hidden font-mono text-[10px] border border-line rounded px-2 py-1.5 bg-inset"></div></div><div class="h-[52px] px-4 flex items-center justify-end gap-2 border-t border-line"><button data-action="save-settings" class="px-4 py-1.5 rounded bg-accent hover:bg-accent-hover text-app text-[11px] font-semibold">Сохранить</button></div></div></div>`; }
